backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "courses"
    label: "Courses"
    folder: "courses"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Video Preview URL", name: "video", widget: "string" }
      - { label: "Free Trial URL", name: "trial", widget: "string" }
      - { label: "Purchase Link", name: "purchase", widget: "string" }
