backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "courses"
    label: "Courses"
    folder: "courses"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Video URL", name: "video", widget: "string" }
      - {
          label: "Trial Link",
          name: "trial",
          widget: "string",
          required: false,
        }
      - {
          label: "Purchase Link",
          name: "purchase",
          widget: "string",
          required: false,
        }
      - {
          label: "Course Type",
          name: "type",
          widget: "select",
          options: ["free", "free trial", "paid"],
        }
      - { label: "Price", name: "price", widget: "string", required: false }
